# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ml.proto',
  package='api.v1',
  syntax='proto3',
  serialized_options=_b('Z\020api/v1/mlService'),
  serialized_pb=_b('\n\x08ml.proto\x12\x06\x61pi.v1\"9\n\rDigestRequest\x12\x1a\n\x04role\x18\x01 \x01(\x0e\x32\x0c.api.v1.Role\x12\x0c\n\x04path\x18\x02 \x01(\t\"\x1e\n\x0e\x44igestResponse\x12\x0c\n\x04news\x18\x01 \x03(\t\"8\n\x0cTrendRequest\x12\x1a\n\x04role\x18\x01 \x01(\x0e\x32\x0c.api.v1.Role\x12\x0c\n\x04path\x18\x02 \x01(\t\" \n\rTrendResponse\x12\x0f\n\x07incites\x18\x01 \x03(\t*\x1d\n\x04Role\x12\t\n\x05OWNER\x10\x00\x12\n\n\x06\x42OOKER\x10\x01\x32~\n\tMlService\x12\x39\n\x06\x44igest\x12\x15.api.v1.DigestRequest\x1a\x16.api.v1.DigestResponse\"\x00\x12\x36\n\x05Trend\x12\x14.api.v1.TrendRequest\x1a\x15.api.v1.TrendResponse\"\x00\x42\x12Z\x10\x61pi/v1/mlServiceb\x06proto3')
)

_ROLE = _descriptor.EnumDescriptor(
  name='Role',
  full_name='api.v1.Role',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OWNER', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOKER', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=203,
  serialized_end=232,
)
_sym_db.RegisterEnumDescriptor(_ROLE)

Role = enum_type_wrapper.EnumTypeWrapper(_ROLE)
OWNER = 0
BOOKER = 1



_DIGESTREQUEST = _descriptor.Descriptor(
  name='DigestRequest',
  full_name='api.v1.DigestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role', full_name='api.v1.DigestRequest.role', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='api.v1.DigestRequest.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=77,
)


_DIGESTRESPONSE = _descriptor.Descriptor(
  name='DigestResponse',
  full_name='api.v1.DigestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='news', full_name='api.v1.DigestResponse.news', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=109,
)


_TRENDREQUEST = _descriptor.Descriptor(
  name='TrendRequest',
  full_name='api.v1.TrendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role', full_name='api.v1.TrendRequest.role', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='api.v1.TrendRequest.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=167,
)


_TRENDRESPONSE = _descriptor.Descriptor(
  name='TrendResponse',
  full_name='api.v1.TrendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='incites', full_name='api.v1.TrendResponse.incites', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=201,
)

_DIGESTREQUEST.fields_by_name['role'].enum_type = _ROLE
_TRENDREQUEST.fields_by_name['role'].enum_type = _ROLE
DESCRIPTOR.message_types_by_name['DigestRequest'] = _DIGESTREQUEST
DESCRIPTOR.message_types_by_name['DigestResponse'] = _DIGESTRESPONSE
DESCRIPTOR.message_types_by_name['TrendRequest'] = _TRENDREQUEST
DESCRIPTOR.message_types_by_name['TrendResponse'] = _TRENDRESPONSE
DESCRIPTOR.enum_types_by_name['Role'] = _ROLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DigestRequest = _reflection.GeneratedProtocolMessageType('DigestRequest', (_message.Message,), {
  'DESCRIPTOR' : _DIGESTREQUEST,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:api.v1.DigestRequest)
  })
_sym_db.RegisterMessage(DigestRequest)

DigestResponse = _reflection.GeneratedProtocolMessageType('DigestResponse', (_message.Message,), {
  'DESCRIPTOR' : _DIGESTRESPONSE,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:api.v1.DigestResponse)
  })
_sym_db.RegisterMessage(DigestResponse)

TrendRequest = _reflection.GeneratedProtocolMessageType('TrendRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRENDREQUEST,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:api.v1.TrendRequest)
  })
_sym_db.RegisterMessage(TrendRequest)

TrendResponse = _reflection.GeneratedProtocolMessageType('TrendResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRENDRESPONSE,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:api.v1.TrendResponse)
  })
_sym_db.RegisterMessage(TrendResponse)


DESCRIPTOR._options = None

_MLSERVICE = _descriptor.ServiceDescriptor(
  name='MlService',
  full_name='api.v1.MlService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=234,
  serialized_end=360,
  methods=[
  _descriptor.MethodDescriptor(
    name='Digest',
    full_name='api.v1.MlService.Digest',
    index=0,
    containing_service=None,
    input_type=_DIGESTREQUEST,
    output_type=_DIGESTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Trend',
    full_name='api.v1.MlService.Trend',
    index=1,
    containing_service=None,
    input_type=_TRENDREQUEST,
    output_type=_TRENDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MLSERVICE)

DESCRIPTOR.services_by_name['MlService'] = _MLSERVICE

# @@protoc_insertion_point(module_scope)
